language: node_js

node_js:
  - "14.17.6"

branches:
  only:
    - main

cache:
  directories:
    - node_modules
    - ~/.npm

install:
  - npm ci

script:
  - "npm test"

notifications:
  email:
    recipients:
      - estefania_8_3@hotmail.com

before_install:
  - npm i npm@7.23.0
  - npm i node-fetch@2.6.1
  - npm i marked@3.0.4

jobs:
  include:
    - stage: test
      script: npm test
      script: npm eslint
