language: node_js
node_js:
  - "14.17.6"
branches:
only:
  - main
cache:
  directories:
    - node_modules
install:
  - npm ci
script:
  - "npm test"
notifications:
  email:
    recipients:
      - estefania_8_3@hotmail.com
